=== AlpetGexh/UPZ-TIT/Semestri_6/Webi Dinamik/Ushtrime_old/Java 11/Ushtrimet/Grupi1/gazeta.dtd
<!DOCTYPE gazeta [

<!ELEMENT gazeta (artikulli+)>
<!ELEMENT artikulli (kryetitulli, kryesuesi, trupi, shenimet)>
<!ELEMENT kryetitulli (#PCDATA)>
<!ELEMENT kryesuesi (#PCDATA)>
<!ELEMENT trupi (#PCDATA)>
<!ELEMENT shenimet (#PCDATA)>

<!ATTLIST artikulli autori CDATA #REQUIRED>
<!ATTLIST artikulli editori CDATA #IMPLIED>
<!ATTLIST artikulli data CDATA #IMPLIED>
<!ATTLIST artikulli botimi CDATA #IMPLIED>

<!ENTITY gazeta "Koha Ditore">
<!ENTITY publikuesi "Botimet Koha">
<!ENTITY copyright "Copyright 2000 Botimet Koha">

]>

=== AlpetGexh/UPZ-TIT/Semestri_6/Webi Dinamik/Ushtrime_old/Java 11/Ushtrimet/Grupi1/gazeta.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<!DOCTYPE gazeta SYSTEM "gazeta.dtd">
<gazeta>
	<artikulli autori = "Autori 1" editori = "Editori 1">
		<kryetitulli>Titulli 1</kryetitulli>
		<kryesuesi>Filan Fisteku</kryesuesi>
		<trupi>Permbajtja e artikullit 1</trupi>
		<shenimet>Shenime shtese</shenimet>
	</artikulli>
	
	<artikulli autori = "Autori 2" data = "06.05.2020">
		<kryetitulli>Titulli 2</kryetitulli>
		<kryesuesi>Test Testi</kryesuesi>
		<trupi>Permbajtja e artikullit 2</trupi>
		<shenimet>Shenime shtese</shenimet>
	</artikulli>
</gazeta>
