=== AlpetGexh/UPZ-TIT/Semestri_6/Webi Dinamik/Ushtrime_old/Ushtrime - Java XIV/Ushtrime/emails.xsd
<?xml version = "1.0" encoding = "UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!--llojet e te dhenave (custom types)-->
	
	<xs:simpleType name = "nameType">
		<xs:restriction base = "xs:string">
			<xs:pattern value = "([A-Za-z])+[ ]([A-Za-z])+"/>
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name = "emailType">
		<xs:restriction base = "xs:string">
			<xs:pattern value = "([A-Za-z0-9._])+[@]([A-Za-z])+[.]([A-Za-z])+"/>
		</xs:restriction>
	</xs:simpleType>

	
	<!--elementet e thjeshta-->
	<xs:element name = "body" type = "xs:string"/>
	
	<xs:element name = "date" type = "xs:date"/>
	
	<xs:element name = "subject" type = "xs:string"/>
	
	<xs:element name = "name" type = "nameType"/>
	
	<xs:element name = "emailAddress" type = "emailType"/>
	
	
	<!--lloj kompleks i elementit-->
	<xs:complexType name = "personEmail">
		<xs:sequence>
			<xs:element ref = "name"/>
			<xs:element ref = "emailAddress"/>
		</xs:sequence>
	</xs:complexType>
	
	<!--elementet kompleske-->
	<xs:element name = "from" type = "personEmail"/>
	
	<xs:element name = "to" type = "personEmail"/>
	
	<xs:element name = "header">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref = "from"/>
				<xs:element ref = "to" maxOccurs = "unbounded"/>
				<xs:element ref = "date"/>
				<xs:element ref = "subject" minOccurs = "0"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name = "email">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref = "header"/>
				<xs:element ref = "body"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
	<xs:element name = "emails">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref = "email" maxOccurs = "unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== AlpetGexh/UPZ-TIT/Semestri_6/Webi Dinamik/Ushtrime_old/Ushtrime - Java XIV/Ushtrime/emails (2).xml
<?xml version = "1.0" encoding = "UTF-8"?>

<?xml-stylesheet type = "text/xsl" href="emails.xslt"?>

<emails xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "emails.xsd">
	<email>
		<header>
			<from>
				<name>John Doe</name>
				<emailAddress>john.doe@gmail.com</emailAddress>
			</from>
			<to>
				<name>Joe Doe</name>
				<emailAddress>joe.doe@hotmail.com</emailAddress>
			</to>
			<to>
				<name>Michelle Kellerman</name>
				<emailAddress>m.kellerman@hotmail.com</emailAddress>
			</to>
			<date>2020-04-25</date>
			<subject>Hello!</subject>
		</header>
		<body>This is message one!</body>

	</email>
	
	<email>
		<header>
			<from>
				<name>Fred Murray</name>
				<emailAddress>fred.m@gmail.com</emailAddress>
			</from>
			<to>
				<name>Jack Simpson</name>
				<emailAddress>j.simpson@hotmail.com</emailAddress>
			</to>
			<date>2020-03-22</date>
			<subject>Re: Subject1</subject>
		</header>
		<body>Excellent...</body>
	</email>
	
	<email >
		<header>
			<from>
				<name>Noah Ross</name>
				<emailAddress>noah.ross@live.com</emailAddress>
			</from>
			<to>
				<name>Emma Grant</name>
				<emailAddress>emma.gt@hotmail.com</emailAddress>
			</to>
			<date>2020-01-21</date>
			<subject>Results</subject>
		</header>
		<body>Results from exam 1...</body>
	</email>
	
	<email>
		<header>
			<from>
				<name>Emily Wilson</name>
				<emailAddress>emily.watson@gmail.com</emailAddress>
			</from>
			<to>
				<name>Mia Scott</name>
				<emailAddress>mia.scott@gmail.com</emailAddress>
			</to>
			<date>2019-05-15</date>
			<subject>Decision</subject>
		</header>
		<body>Attached with this email you can find the council's decision...</body>
	</email>
	
	<email>
		<header>
			<from>
				<name>Ella Reid</name>
				<emailAddress>e.reid@hotmail.com</emailAddress>
			</from>
			<to>
				<name>Grace Henderson</name>
				<emailAddress>grace.henderson@gmail.com</emailAddress>
			</to>
			<date>2018-01-15</date>
			<subject>Report</subject>
		</header>
		<body>This is the report of April month...</body>
	</email>
</emails>
